# Generated by Django 4.0.5 on 2022-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='LFOfreq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preset',
            name='LFOtype',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preset',
            name='attackTime',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=2),
        ),
        migrations.AddField(
            model_name='preset',
            name='filterCutoff',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='preset',
            name='filterType',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preset',
            name='oscillatorType',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preset',
            name='releaseTime',
            field=models.DecimalField(decimal_places=1, default=0.3, max_digits=2),
        ),
        migrations.AddField(
            model_name='preset',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
